"use client";
import Header from "@/components/header/Header";
import "./globals.scss";
import CursorWrapper from "@/components/animations/CursorWrapper";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Graph and Co",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* <body className={inter.className}> */}
            <body>
                {/* <CursorWrapper /> */}
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
