"use client";
import Header from "@/components/header/Header";
import "./globals.scss";
import { gsap } from "gsap";
import Cursor from "@/components/Cursor";
import { useEffect, useRef } from "react";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Graph and Co",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const circleRefs = useRef([]);

    // reset on re-renders
    circleRefs.current = [];

    useEffect(() => {
        const { innerWidth, innerHeight } = window;
        circleRefs.current.forEach((ref) =>
            ref.moveTo(innerWidth / 2, innerHeight / 2)
        );

        const onMove = ({ clientX, clientY }) => {
            circleRefs.current.forEach((ref) => ref.moveTo(clientX, clientY));
        };

        window.addEventListener("pointermove", onMove);

        return () => window.removeEventListener("pointermove", onMove);
    }, []);

    const addCircleRef = (ref) => {
        if (ref) {
            circleRefs.current.push(ref);
        }
    };

    return (
        <html lang="en">
            {/* <body className={inter.className}> */}
            <body>
                <div className="cursors hidden md:flex">
                    <Cursor size="sm" ref={addCircleRef} delay={0} />
                    <Cursor size="md" ref={addCircleRef} delay={0.1} />
                    <Cursor size="lg" ref={addCircleRef} delay={0.2} />
                </div>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
